### PR TITLE
Promokit

### PR DESCRIPTION
**Pull request by promokit**
Added logo image dimension values

### CODE REVIEW

**Comment by samberrry** [comment]
@promokit 
thanks for reaching out. 
Seems you added files from our Pro version. The files, doc and everything inside the Pro version is not free, and is licensed to Binshops and is prohibited to be open-source, so it can not be published publicly on any repository or any marketplace. 

**Please delete your Pull Request completely**, and also your public branch on your fork:
https://github.com/promokit/prestashop-rest/tree/promokit

**poromokit** branch

However, if you want to contribute to the repository you should create a branch from **develop** branch, and please give a meaningful name related to the feature you worked on.

Many thanks in advance.

**Comment by samberrry** [comment]
> Weird, because I have got all files from your GitHub repository. I don't have a Pro version of your module.

@promokit how did you add the files in your commit: 'Add missed files'

there is not such files on github and publicly available? 
how did you get them?

**Comment by promokit** [comment]
I had a module version cloned from GitHub some time ago. Today I have cloned it once again and those files appeared in the project. So I have added them to my existing project and pushed it back to GitHub.

**Comment by samberrry** [comment]
> I had a module version cloned from GitHub some time ago. Today I have cloned it once again and those files appeared in the project. So I have added them to my existing project and pushed it back to GitHub.

@promokit strange, because we do not have and we did not have any commit or branch to contain these files.
Anyway, thanks. And please remove/delete this pull request completely, because it has the changes and files. Please be sure that this pull request is not available publicly.

Many thanks, and sorry for the inconvenience.

**Comment by samberrry** [comment]
if you have any other question you can directly contact me: 

sam@binshops.com

**Comment by promokit** [comment]
Yes, it's already removed

**Comment by samberrry** [comment]
> Yes, it's already removed

thank you.

**Comment by promokit** [comment]
No problem

**Pull request closed without merging**
